# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NKS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_initial', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=10)),
                ('residential_phone', models.CharField(max_length=11)),
                ('cell_phone', models.CharField(max_length=11)),
                ('other', models.CharField(max_length=30)),
            ],
        ),
    ]
