# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180713_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='nks',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
