# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_nks_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nks',
            old_name='other',
            new_name='operational_number',
        ),
    ]
