# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180716_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nks',
            old_name='operational_number',
            new_name='operator_number',
        ),
    ]
